const mongoose = require('mongoose');

/**
 * Sub-schema for individual repository summaries generated by LLM analysis.
 */
const RepoSummarySchema = new mongoose.Schema({
  name: { type: String, required: true },
  description: { type: String, default: null },
  languages: { type: [String], default: [] },
  techStack: { type: [String], default: [] },
  architecturePatterns: { type: [String], default: [] },
  summary: { type: String, required: true },
});

/**
 * Root GitHub Report Schema.
 * Stores deterministic heuristic profiling scores alongside LLM-generated repository summaries.
 * Built for quick retrieval, consistency, and easy frontend mapping.
 */
const GithubReportSchema = new mongoose.Schema(
  {
    username: {
      type: String,
      required: true,
      trim: true,
      lowercase: true,
      index: true,
    },
    profile: {
      name: { type: String, default: null },
      avatarUrl: { type: String, default: null },
      bio: { type: String, default: null },
      publicRepos: { type: Number, default: 0 },
      followers: { type: Number, default: 0 },
    },
    heuristics: {
      cleanlinessScore: { type: Number, required: true, min: 0, max: 100 },
      diversityScore: { type: Number, required: true, min: 0, max: 100 },
      consistencyScore: { type: Number, required: true, min: 0, max: 100 },
      overallScore: { type: Number, required: true, min: 0, max: 100 },
      checks: [
        {
          name: { type: String, required: true },
          passed: { type: Boolean, required: true },
          points: { type: Number, required: true },
          detail: { type: String, default: null },
        },
      ],
    },
    summaries: {
      type: [RepoSummarySchema],
      default: [],
    },
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

module.exports = mongoose.model('GithubReport', GithubReportSchema);
